### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jacobhuesman** [jacobhuesman/ros_vrep_plugin#1]
- [ ] Change current file check to use `simDoesFileExist` API function
- [ ] Add simLoadScene service, maybe do a dynamic reconfigure?
- [ ] Change current wheel joints object to a generic joints object
- [ ] Add set joint velocity, maybe force for linear actuators?
- [ ] Add collision check functionality
  - [ ] Collision with rock
  - [ ] Collision with crater
- [ ] Create scoring system, points docked for each rock, crater hit and how close they get to hitting a crater or rock
  - [ ] Possibly use highest costmap value that the robot occupies as the scoring mechanism
